# DB-GPT Docker Compose Configuration
# Using local images to avoid network issues
services:
  webserver:
    image: eosphorosai/dbgpt-openai:latest
    container_name: dbgpt-webserver
    command: dbgpt start webserver --config /app/configs/dbgpt-overdue-analysis.toml
    environment:
      - SILICONFLOW_API_KEY=sk-stwdcstqnkcztrsqsrmosrcpekiacrualyzzvsgfmzjvuurv
      - MYSQL_PASSWORD=Weshare@2025
      - MYSQL_HOST=10.10.19.1
      - MYSQL_PORT=9030
      - MYSQL_DATABASE=dbgpt
      - MYSQL_USER=ai_user1
    volumes:
      - ./configs:/app/configs
      - ./data:/data
      - ./models:/app/models
      - dbgpt-data:/app/pilot/data
      - dbgpt-message:/app/pilot/message
    ports:
      - "5670:5670"
    restart: unless-stopped

volumes:
  dbgpt-data:
  dbgpt-message: